name: Pylint and tests

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Analysing the code with pylint
        run: |
          pylint $(git ls-files '*.py')
      - name: Running tests
        run: |
          pytest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Docker container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DOCKER_HOST }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          port: 22
          script: |
            docker pull yourusername/yourimage:latest
            docker run -d -p 80:80 yourusername/yourimage:latest
